import type { Metadata } from "next";
import localFont from "next/font/local";
import {Header} from "../components_/Headers";
import { Outfit, Nunito } from 'next/font/google';
import { ToastContainer } from "@/lib/Toast";
import { Toaster } from "@/components/ui/toaster"
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs';
const outfit = Outfit({
  subsets: ['latin'], // Specify subsets (e.g., latin, cyrillic) if needed
  weight: ["200", "300", "400",  "500",  "600", "700", "800", "900" ], // Specify the weights you want to include
});
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Resumer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // {geistSans.variable} ${geistMono.variable}
  return (
    <html lang="en">
      <ClerkProvider>

      <body
        className={`${outfit.className} bg-white`}
      >
        <Header/>
        {children}
        <Toaster/>
      </body>
      </ClerkProvider>
    </html>
  );
}
